apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: airflow
spec:
  containers:
    - image: ubuntu:latest
      name: workload-identity-test
      command: ["sleep", "infinity"]
  serviceAccountName: sa-gke
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
